default: &default
  adapter: postgresql
  port: 5432
  encoding: utf8

docker: &docker
  <<: *default
  host: 127.0.0.1
  username: postgres
  password:

development:
  <<: *docker
  database: x_review_dev

test:
  <<: *docker
  database: x_review_test

production:
  <<: *default
  database: x_review
